version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: coffeemachine_postgres
    restart: always
    environment:
      POSTGRES_USER: coffee_user
      POSTGRES_PASSWORD: coffee_pass
      POSTGRES_DB: coffeemachine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d # Добавление SQL-скриптов для инициализации

volumes:
  postgres_data:
